### ISSUE TITLE
'vtkpython' is not recognized as an internal or external command, operable program or batch file.

### ISSUE THREAD

**Issue by vignesh-sivakumar** [dave3d/dicom2stl#6]
Hi,
I installed both vtk and simpleITK using pip and the versions of the same are shown below. 

Name: vtk
Version: 8.1.2
Summary: VTK is an open-source toolkit for 3D computer graphics, image processing, and visualization
Home-page: https://vtk.org/
Author: VTK Community
Author-email: vtk-developers@vtk.org
License: BSD
Location: c:\users\vignesh\anaconda3\lib\site-packages
Requires:
Required-by:

Name: SimpleITK
Version: 1.2.4
Summary: SimpleITK is a simplified interface to the Insight Toolkit (ITK) for image registration and segmentation
Home-page: http://simpleitk.org/
Author: Insight Software Consortium
Author-email: insight-users@itk.org
License: Apache
Location: c:\users\vignesh\anaconda3\lib\site-packages
Requires:
Required-by:

But even then, "vtkpython dicom2stl.py -t bone -o bone.stl ct.zip" in the anaconda prompt in windows produces the error "  'vtkpython' is not recognized as an internal or external command, operable program or batch file. "

Assist needed. Thank you.

**Comment by dave3d** [comment]
I hope you figured it out.  Presumably you just used 'python' instead of 'vtkpython'.  I wrote that documentation a long time ago, back when I built vtk/python by hand.  So VTK would create a vtkpython executable.  These days with pip, you don't need to build VTK.  So I should probably update the docs.

Cheers,
Dave
